<script src="/temp/admin/libs/jquery/dist/jquery.min.js"></script>
<script src="/temp/admin/assets/js/bootstrap.bundle.min.js"></script>
<script src="/temp/build/js/admin.min.js"></script>
{{-- <script src="/temp/build/js/main.min.js"></script> --}}
<script src="/temp/build/js/validate.min.js"></script>
<script src="/temp/admin/assets/js/owl.carousel.min.js"></script>
<script src="/temp/admin/assets/vendor/libs/jquery/jquery.js"></script>
<script src="/temp/admin/assets/vendor/libs/popper/popper.js"></script>
<script src="/temp/admin/assets/vendor/js/bootstrap.js"></script>
<script src="/temp/admin/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
<script src="/temp/admin/assets/vendor/js/menu.js"></script>
<script src="/temp/admin/assets/vendor/libs/apex-charts/apexcharts.js"></script>
<script src="/temp/admin/assets/js/main.js"></script>
<script src="/temp/admin/assets/js/dashboards-analytics.js"></script>
<script async defer src="https://buttons.github.io/buttons.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
